### ISSUE TITLE
Switch to pnpm and improve build process

### ISSUE THREAD

**Issue by youngchingjui** [youngchingjui/issue-to-pr#311]
## Current Situation
Currently, the deployment workflow uses npm for package management and doesn't clean the `node_modules` directory before builds.

## Proposed Changes
1. Switch from npm to pnpm for:
   - Faster installation times
   - Better disk space usage
   - More reliable dependency resolution
   - Strict dependency management

2. Add cleanup step in the deployment workflow:
   - Clear `node_modules` before fresh installation
   - Ensure clean state for each deployment

## Implementation Details
Update `.github/workflows/deploy.yml`:
```yaml
# Before installing dependencies
- name: Clean node_modules
  run: rm -rf node_modules
  working-directory: /home/ec2-user/issue-to-pr/

# Update package manager commands
- name: Install pnpm
  run: npm install -g pnpm

- name: Install dependencies
  run: pnpm install
  working-directory: /home/ec2-user/issue-to-pr/

- name: Build project
  run: pnpm run build
  working-directory: /home/ec2-user/issue-to-pr/
```

## Additional Tasks
1. Update package-lock.json to pnpm-lock.yaml
2. Update documentation to reflect pnpm usage
3. Add pnpm version to the workflow for consistency

## Benefits
- More reliable builds with clean node_modules
- Faster installations with pnpm
- Better disk space usage on the EC2 instance
- Stricter dependency management
