### ISSUE TITLE
pnpm seems to re-download all packages every test run

### ISSUE THREAD

**Issue by youngchingjui** [youngchingjui/issue-to-pr#426]
in our test workflow on github, one of the steps is to setup pnpm. 

Not sure if this is because it is running on our self-hosted runner on our amazon ec2 linux image.

But eveyrtime this workflow is run, all the packages are re-downloaded. 

I thought pnpm was supposed to use packages from cache. 

This really slows down the testing process.

See these logs:

```
0s
3m 12s
Run pnpm/action-setup@v4
  with:
    version: 10.6.4
    run_install: true
    dest: ~/setup-pnpm
    package_json_file: package.json
    standalone: false
Running self-installer...
  Progress: resolved 1, reused 0, downloaded 0, added 0
  Packages: +1
  +
  Progress: resolved 1, reused 1, downloaded 0, added 1, done
  dependencies:
  + pnpm 10.6.4 (10.11.0 is available)
  Done in 774ms
Installation Completed!
Running pnpm recursive install...
  Lockfile is up to date, resolution step is skipped
  Progress: resolved 1, reused 0, downloaded 0, added 0
  .                                        | +978 ++++++++++++++++++++++++++++++++
  Progress: resolved 978, reused 0, downloaded 15, added 2
  Progress: resolved 978, reused 0, downloaded 39, added 11
  Progress: resolved 978, reused 0, downloaded 71, added 60
  Progress: resolved 978, reused 0, downloaded 83, added 76
  Progress: resolved 978, reused 0, downloaded 103, added 83
  Progress: resolved 978, reused 0, downloaded 103, added 84
  Progress: resolved 978, reused 0, downloaded 113, added 85
  Progress: resolved 978, reused 0, downloaded 118, added 87
  Progress: resolved 978, reused 0, downloaded 153, added 98
  Progress: resolved 978, reused 0, downloaded 167, added 104
  Progress: resolved 978, reused 0, downloaded 167, added 105
  Progress: resolved 978, reused 0, downloaded 172, added 108
  Progress: resolved 978, reused 0, downloaded 182, added 108
  Progress: resolved 978, reused 0, downloaded 188, added 111
  Progress: resolved 978, reused 0, downloaded 188, added 112
  Progress: resolved 978, reused 0, downloaded 204, added 115
  Progress: resolved 978, reused 0, downloaded 216, added 118
  Progress: resolved 978, reused 0, downloaded 216, added 119
  Progress: resolved 978, reused 0, downloaded 321, added 172
  Progress: resolved 978, reused 0, downloaded 349, added 182
```
